name: Check modules

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
    branches: [master]

jobs:
  validate_modules:
    name: Validate module versions
    runs-on: ubuntu-18.04
    env:
      GIT_BASE_SHA: ${{ github.event.pull_request.base.sha }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
    steps:
      - uses: actions/checkout@v1
      - name: Verify module versions do not exist yet
        run: ./tools/publisher -bucket=tfmodules.lolcatz.de -region=ap-southeast-1 -check -diff=${GIT_BASE_SHA}
