name: Publish

on:
  push:
    branches: [master, publisher]

jobs:
  validate_modules:
    name: Publish modules
    runs-on: ubuntu-18.04
    env:
      GIT_BASE_SHA: ${{ github.event.before }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
    steps:
      - uses: actions/checkout@v1
      - run: echo ${GIT_BASE_SHA}
      # - name: Publish modules
      #   run: |
      #     ./tools/publisher \
      #       -publish \
      #       -bucket=${BUCKET_NAME} \
      #       -region=${BUCKET_REGION} \
      #       -web-url=http://${BUCKET_NAME} \
      #       -diff=
