name: Publish

on:
  push:
    branches:
      - master

jobs:
  validate_modules:
    name: Publish modules
    runs-on: ubuntu-18.04
    env:
      GIT_BASE_SHA: ${{ github.event.before }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: tfmodules.lolcatz.de
      BUCKET_REGION: ap-southeast-1
    steps:
      - uses: actions/checkout@v1
      - name: Publish modules
        run: |
          ./tools/publisher \
            -publish \
            -bucket=${BUCKET_NAME} \
            -region=${BUCKET_REGION} \
            -web-url=http://${BUCKET_NAME} \
            -diff=${GIT_BASE_SHA}
